package de.coldtea.anidex.content.domain.model

enum class AnimeGenre(val genreId: Int, val genreName: String) {
    ACTION(1, "Action"),
    ADVENTURE(2, "Adventure"),
    CARS(3, "Cars"),
    COMEDY(4, "Comedy"),
    AVANTE(5,"Avante Garde"),
    DEMONS(6, "Demons"),
    MYSTERY(7, "Mystery"),
    DRAMA(8, "Drama"),
    ECCHI(9, "Ecchi"),
    FANTASY(10, "Fantasy"),
    GAME(11, "Game"),
    HENTAI(12, "Hentai"),
    HISTORICAL(13, "Historical"),
    HORROR(14, "Horror"),
    KIDS(15, "Kids"),
    MARTIAL_ARTS(17, "Martial Arts"),
    MECHA(18, "Mecha"),
    MUSIC(19, "Music"),
    PARODY(20, "Parody"),
    SAMURAI(21, "Samurai"),
    ROMANCE(22, "Romance"),
    SCHOOL(23, "School"),
    SCI_FI(24, "Sci Fi"),
    SHOUJO(25, "Shoujo"),
    GIRLS_LOVE(26, "Girls Love"),
    SHOUNEN(27, "Shounen"),
    BOYS_LOVE(28, "Boys Love"),
    SPACE(29, "Space"),
    SPORTS(30, "Sports"),
    SUPER_POWER(31, "Super Power"),
    VAMPIRE(32, "Vampire"),
    HAREM(35, "Harem"),
    SLICE_OF_LIFE(36, "Slice Of Life"),
    SUPERNATURAL(37, "Supernatural"),
    MILITARY(38, "Military"),
    POLICE(39, "Police"),
    PSYCHOLOGICAL(40, "Psychological"),
    SUSPENSE(41, "Seinen"),
    SEINEN(42, "Josei"),
    JOSEI(43, "Doujinshi"),
    AWARD_WINNING(46, "Award Winning"),
    GOURMET(47, "Gourmet"),
    WORK_LIFE(48, "Work Life"),
    EROTICA(49, "Erotica"),
}